#-------------------------------
# General Site Settings
title: Learning
description: Just a blog for learning something about deep learning.


#-------------------------------
# Author Settings
author:
  name: Sk4Dl
  say-hello: Hello, I’m <strong>Sk4Dl</strong>
  bio: A postgraduate student of Harbin Institude of Technology, Shenzhen. A deeping learning amateur.
